### ISSUE TITLE
Run shellcheck in Travis

### ISSUE THREAD

**Issue by rugk** [matejak/argbash#33]
You might want to run shellcheck over al your `.sh` files in your unit tests in order to assure they are good.

I do it [like that](https://github.com/rugk/borg-cron-helper/blob/master/tests/testShellcheck.sh).

**Comment by rubicks** [comment]
:+1: strongly agree; this would be a great addition. Consider also running shellcheck on some generated snippets as part of a test unit.

**Comment by edannenberg** [comment]
The docker image for shellcheck is well maintained, `.travis.yml` we currently use:

```yaml
sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
 - docker run -w /scripts -v $(pwd):/scripts koalaman/shellcheck -x path/*.sh path2/*.sh
```

Just need to update the paths it should check in the last line.
